# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('UseRcppStrings_rcpp_hello_world', PACKAGE = 'UseRcppStrings')
}

testTrim <- function(str) {
    .Call('UseRcppStrings_testTrim', PACKAGE = 'UseRcppStrings', str)
}

