// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RcppStrings_RcppExports_h
#define RcppStrings_RcppExports_h

#include <Rcpp.h>

namespace RcppStrings {

    using namespace Rcpp;

    namespace {
        void validateExported(const std::string& sig) {
            static bool(*p_validateExported)(const std::string&) = Rcpp::GetCppCallable("RcppStrings", "RcppStrings_RcppExports", "RcppExports_validateExported");
            if (!p_validateExported(sig))
                throw Rcpp::function_not_exported("Function '" + sig + "' not found in RcppStrings");
        }
    }

    inline CharacterVector stringTrim(CharacterVector input, std::string side = "both") {
        static CharacterVector(*p_stringTrim)(CharacterVector,std::string) = NULL;
        if (p_stringTrim == NULL) {
            validateExported("CharacterVector(*stringTrim)(CharacterVector,std::string)");
            p_stringTrim = Rcpp::GetCppCallable("RcppStrings", "RcppStrings_RcppExports", "stringTrim");
        }
        return p_stringTrim(input,side);
    }

}

#endif // RcppStrings_RcppExports_h
