// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __RcppStrings_h__
#define __RcppStrings_h__

#include "RcppStrings_RcppExports.h"

#endif // __RcppStrings_h__
