// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

CharacterVector stringTrim(CharacterVector input, std::string side = "both");

static bool validateExported(const std::string& sig) {
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("CharacterVector(*stringTrim)(CharacterVector,std::string)");
    }
    return signatures.find(sig) != signatures.end();
}

RCPP_MODULE(RcppStrings_RcppExports) {
    Rcpp::function("stringTrim", &stringTrim, Rcpp::List::create(Rcpp::Named("input"), Rcpp::Named("side") = "both"));
    Rcpp::function("RcppExports_validateExported", &validateExported);
}
