// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP UseRcppStrings_rcpp_hello_world() {
BEGIN_RCPP
    List result = rcpp_hello_world();
    return Rcpp::wrap(result);
END_RCPP
}
// testTrim
Rcpp::CharacterVector testTrim(Rcpp::CharacterVector str);
RcppExport SEXP UseRcppStrings_testTrim(SEXP strSEXP) {
BEGIN_RCPP
    Rcpp::CharacterVector str = Rcpp::as<Rcpp::CharacterVector >(strSEXP);
    Rcpp::CharacterVector result = testTrim(str);
    return Rcpp::wrap(result);
END_RCPP
}
