# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393


#' Trim whitespace from start and end of string
#' 
#' @usage trim(input, side = "both")
#' @param input input character vector
#' @param side side on which whitespace is removed (left, right, or both)
#' @return character vector with leading and trailing whitespace removed
#' @examples 
#' \dontrun{
#' trimString("\n\nString with trailing and leading white space \t")
#' }
stringTrim<- function(input, side) {}

Rcpp::loadModule("RcppStrings_RcppExports", 
    what = c("stringTrim"))
