# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393


#' Trim whitespace from start and end of string
#' 
#' @usage trimAll(input)
#' @param input input character vector
#' @return character vector with leading and trailing whitespace removed
#' @examples 
#' \dontrun{
#' trimAll("\n\nString with trailing and leading white space \t")
#' }
trimAll<- function(input) {}


#' Trim whitespace from start of string
#' 
#' @usage trimLeft(input)
#' @param input input character vector
#' @return character vector with leading whitespace removed
#' @examples 
#' \dontrun{
#' trimLeft("\n\nString with leading white space")
#' }
trimLeft<- function(input) {}


#' Trim whitespace from end of string
#' 
#' @usage trimRight(input)
#' @param input input character vector
#' @return character vector with trailing whitespace removed
#' @examples 
#' \dontrun{
#' trimRight("\n\nString with trailing white space")
#' }
trimRight<- function(input) {}

Rcpp::loadModule("RcppStrings_RcppExports", 
    what = c("trimAll",
             "trimLeft",
             "trimRight"))
